// THIS IS AN EXAMPLE FILE OF HOW TO USE RBS

// move around
MOVE 10,10,90 4000
// follow syntax: MOVE x,y,theta timeout
// example moves to coordinate 10,10 heading 90 and times out after 4 seconds

// use intake
INTAKE forward
INTAKE reverse
INTAKE stop

// use elevator
LEVEL up
LEVEL middle
LEVEL down

// use alignment mech
ALIGN out
ALIGN in